##############################################################################
# Script Name - desc_variable_names.R
# Author - Shubhojyoti Bhattacharya
#
# This script creates a character vector (of length 66). Each entry
# represents the descriptive name for the variables in the merged dataset.
# The variable names are in proper sequence that matches their occurence in the
# merged dataset.
#
# This script MUST be present in the current working directory.
##############################################################################

all_data_var_column_names <- c("mean_time_body_acceleration_xaxis", "mean_time_body_acceleration_yaxis", "mean_time_body_acceleration_zaxis", "std_time_body_acceleration_xaxis", "std_time_body_acceleration_yaxis", "std_time_body_acceleration_zaxis", "mean_time_gravity_acceleration_xaxis", "mean_time_gravity_acceleration_yaxis", "mean_time_gravity_acceleration_zaxis", "std_time_gravity_acceleration_xaxis", "std_time_gravity_acceleration_yaxis", "std_time_gravity_acceleration_zaxis", "mean_time_body_acceleration_jerk_xaxis", "mean_time_body_acceleration_jerk_yaxis", "mean_time_body_acceleration_jerk_zaxis", "std_time_body_acceleration_jerk_xaxis", "std_time_body_acceleration_jerk_yaxis", "std_time_body_acceleration_jerk_zaxis", "mean_time_body_angular_velocity_xaxis", "mean_time_body_angular_velocity_yaxis", "mean_time_body_angular_velocity_zaxis", "std_time_body_angular_velocity_xaxis", "std_time_body_angular_velocity_yaxis", "std_time_body_angular_velocity_zaxis", "mean_time_body_angular_velocity_jerk_xaxis", "mean_time_body_angular_velocity_jerk_yaxis", "mean_time_body_angular_velocity_jerk_zaxis", "std_time_body_angular_velocity_jerk_xaxis", "std_time_body_angular_velocity_jerk_yaxis", "std_time_body_angular_velocity_jerk_zaxis", "mean_time_body_acceleration_magnitude", "std_time_body_acceleration_magnitude", "mean_time_gravity_acceleration_magnitude", "std_time_gravity_acceleration_magnitude", "mean_time_body_acceleration_jerk_magnitude", "std_time_body_acceleration_jerk_magnitude", "mean_time_body_angular_velocity_magnitude", "std_time_body_angular_velocity_magnitude", "mean_time_body_angular_velocity_jerk_magnitude", "std_time_body_angular_velocity_jerk_magnitude", "mean_frequency_body_acceleration_xaxis", "mean_frequency_body_acceleration_yaxis", "mean_frequency_body_acceleration_zaxis", "std_frequency_body_acceleration_xaxis", "std_frequency_body_acceleration_yaxis", "std_frequency_body_acceleration_zaxis", "mean_frequency_body_acceleration_jerk_xaxis", "mean_frequency_body_acceleration_jerk_yaxis", "mean_frequency_body_acceleration_jerk_zaxis", "std_frequency_body_acceleration_jerk_xaxis", "std_frequency_body_acceleration_jerk_yaxis", "std_frequency_body_acceleration_jerk_zaxis", "mean_frequency_body_angular_velocity_xaxis", "mean_frequency_body_angular_velocity_yaxis", "mean_frequency_body_angular_velocity_zaxis", "std_frequency_body_angular_velocity_xaxis", "std_frequency_body_angular_velocity_yaxis", "std_frequency_body_angular_velocity_zaxis", "mean_frequency_body_acceleration_magnitude", "std_frequency_body_acceleration_magnitude", "mean_frequency_body_acceleration_jerk_magnitude", "std_frequency_body_acceleration_jerk_magnitude", "mean_frequency_body_angular_velocity_magnitude", "std_frequency_body_angular_velocity_magnitude", "mean_frequency_body_angular_velocity_jerk_magnitude", "std_frequency_body_angular_velocity_jerk_magnitude")
